version: "3"
services:
    nginx:
        image: nginx
        ports:
            - "80:80"
            - "443:443"
        links:
            - php7:php7
            - php5:php5
        volumes:
            - ${dockerdir}/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ${dockerdir}/nginx/servers:/etc/nginx/servers
            - ${dockerdir}/nginx/fastcgi.conf:/etc/nginx/fastcgi.conf
            - ${dockerdir}/nginx/log:/var/log/nginx
            - ${wwwdir}:/var/www/html
    php7:
        build: "./php/php7"
        volumes:
            - ${wwwdir}:/var/www/html
            - ${dockerdir}/php/php7/log:/usr/local/var/log
            - ${dockerdir}/php/php7/php.ini:/usr/local/etc/php/php.ini
        extra_hosts:
            - "api.csiautos.cn:192.168.1.200"
    php5:
        build: "./php/php5"
        volumes:
            - ${wwwdir}:/var/www/html
            - ${dockerdir}/php/php5/log:/usr/local/var/log
            - ${dockerdir}/php/php5/php.ini:/usr/local/etc/php/php.ini
    mysql:
        image: mysql
        ports:
            - "3306:3306"
        volumes:
            - ${dockerdir}/mysql/my.cnf:/etc/mysql/my.cnf
            - ${dockerdir}/mysql/data:/var/lib/mysql
            - ${dockerdir}/mysql/log:/var/log/mysql
        environment:
             - MYSQL_ROOT_PASSWORD=root1234
    redis:
         image: redis
         command: /etc/redis.conf
         ports:
             - "6379:6379"
         volumes:
             - ${dockerdir}/redis/master.conf:/etc/redis.conf
