version: "3"
services:
    nginx:
        image: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ${dockerdir}/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ${dockerdir}/nginx/servers:/etc/nginx/servers
            - ${dockerdir}/nginx/fastcgi.conf:/etc/nginx/fastcgi.conf
            - ${dockerdir}/nginx/log:/var/log/nginx
            - ${wwwdir}:/var/www/html
            - ${dockerdir}/nginx/key:/etc/nginx/key
    php7.1:
        build: "./php/php7.1"
        volumes:
            - ${wwwdir}:/var/www/html
            - ${dockerdir}/php/php7.1/log:/usr/local/var/log
            - ${dockerdir}/php/php7.1/php.ini:/usr/local/etc/php/php.ini
        external_links:
            - nginx:local.iautos.cn
            - nginx:local.data.iautos.cn
    php5.4:
        build: "./php/php5.4"
        volumes:
            - ${wwwdir}:/var/www/html
            - ${dockerdir}/php/php5.4/log:/usr/local/var/log
            - ${dockerdir}/php/php5.4/php.ini:/usr/local/etc/php/php.ini
        extra_hosts:
            - "api.csiautos.cn:192.168.1.200"
            - "u.csiautos.cn:192.168.1.200"
        external_links:
            - nginx:local.iautos.cn
            - nginx:local.data.iautos.cn
            - nginx:local.api.iautos.cn
    php5.6:
        build: "./php/php5.6"
        volumes:
            - ${wwwdir}:/var/www/html
            - ${dockerdir}/php/php5.6/log:/usr/local/var/log
            - ${dockerdir}/php/php5.6/php.ini:/usr/local/etc/php/php.ini
        extra_hosts:
            - "api.csiautos.cn:192.168.1.200"
            - "u.csiautos.cn:192.168.1.200"
        external_links:
            - nginx:local.iautos.cn
            - nginx:local.data.iautos.cn
            - nginx:local.api.iautos.cn
    mysql:
        image: mysql
        ports:
            - "3306:3306"
        volumes:
            - ${dockerdir}/mysql/my.cnf:/etc/mysql/my.cnf
            - ${dockerdir}/mysql/data:/var/lib/mysql
            - ${dockerdir}/mysql/log:/var/log/mysql
        environment:
             - MYSQL_ROOT_PASSWORD=root1234
    redis:
         image: redis
         command: /etc/redis.conf
         ports:
             - "6379:6379"
         volumes:
             - ${dockerdir}/redis/master.conf:/etc/redis.conf
    memcached:
        image: memcached
        ports:
            - "11211:11211"
