nginx:
    image: yidashi/nginx
    ports:
        - "80:80"
        - "443:443"
    links:
        - php:php
    volumes:
        - g:/vagrant/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        - g:/vagrant/docker/nginx/servers:/etc/nginx/servers
        - g:/vagrant/docker/nginx/fastcgi.conf:/etc/nginx/fastcgi.conf
        - g:/vagrant/docker/nginx/server.key:/etc/nginx/server.key
        - g:/vagrant/docker/nginx/server.crt:/etc/nginx/server.crt
    volumes_from:
        - php
php:
    image: yidashi/php
    links:
        - mysql:mysql
    volumes:
        - g:/vagrant/www:/var/www/html
        - g:/vagrant/docker/php/log:/usr/local/var/log
        - g:/vagrant/docker/php/php.ini:/usr/local/etc/php/php.ini
mysql:
    image: yidashi/mysql
    ports:
        - "3306:3306"
    volumes:
        - g:/vagrant/docker/mysql/my.cnf:/etc/mysql/my.cnf
        - g:/vagrant/docker/mysql/data:/var/lib/mysql
        - g:/vagrant/docker/mysql/log:/var/log/mysql
    environment:
         - MYSQL_ROOT_PASSWORD=root1234
websocket:
    image: yidashi/php
    ports:
        - "9502:9502"
    links:
        - mysql:mysql
    volumes:
        - g:/vagrant/www:/var/www/html
    entrypoint: php /var/www/html/autoloan/yii im/server
